version: '3.3'

volumes:
  db-data:

services:
  caddy-gen:
    container_name: caddy-gen
    image: 'wemakeservices/caddy-gen:latest'
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/typebot.io/caddy-certificates:/data/caddy
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - typebot-builder
      - typebot-viewer

  # typebot-db:
  #   image: postgres:16
  #   restart: always
  #   volumes:
  #     - db-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_DB=typebot
  #     - POSTGRES_PASSWORD=typebot
  #   healthcheck:
  #       test: ["CMD-SHELL", "pg_isready -U postgres"]
  #       interval: 5s
  #       timeout: 5s
  #       retries: 5
  typebot-builder:
    image: typebuilder
    restart: always
    # depends_on:
    #   typebot-db:
    #     condition: service_healthy
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
    labels:
      virtual.host: 'typebuilder.advgrowth.com' # change to your domain name
      virtual.port: '3000'
      virtual.tls-email: 'dev@advgrowth.com.br' # change to your email

  typebot-viewer:
    image: typeviewer
    # depends_on:
    #   typebot-db:
    #     condition: service_healthy
    restart: always
    ports:
      - '8081:3000'
    env_file: .env
    labels:
      virtual.host: 'typeviewer.advgrowth.com' # change to your domain name
      virtual.port: '3000'
      virtual.tls-email: 'dev@advgrowth.com.br' # change to your email
